# Generated by Django 4.0.5 on 2022-06-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shavogram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='posted',
        ),
    ]
