# Generated by Django 4.0.5 on 2022-06-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shavogram', '0006_alter_photo_caption_alter_photo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
